function help(tab6)
uicontrol('parent',tab6,'style','text','string','List of Abbreviations:','unit','norm','Position',...
[0.06 0.9 0.9 0.1],'Fontweight','bold','FontSize',20,'FontName','Times New Roman');
uicontrol('parent',tab6,'style','text','string',{'Filtering:';'Sampling frequency (Fs)';...
'lower cutoff frequency (Flow)';'higher cutoff frequency (Fhigh)';'Passband ripple (Rp)';...
'Stopband attenuation (Rs)'},'unit','norm','Position',[0.02 0.6 0.2 0.3],'Fontweight',...
'bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left',...
'ForegroundColor',[0.49 0.18 0.56]);
uicontrol('parent',tab6,'style','text','string',{'Feature Exraction:';'Waveform length (WL)';....
'Principle Component Analysis (PCA)'},'unit','norm','Position',[0.2 0.17 0.2 0.73],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left',...
'ForegroundColor',[0.64 0.08 0.18]);
uicontrol('parent',tab6,'style','text','string',{'Feature Seletion:';'Fisher’s Discriminate Analysis (FDA)';...
'Genetic Algorithm (GA)';'Particle Swarm Optimization (PSO)'},'unit','norm','Position',...
[0.41 0.4 0.2 0.5],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'HorizontalAlignment','left','ForegroundColor','m');
uicontrol('parent',tab6,'style','text','string',{'Clustring:';'Fuzzy C-Means Clustering (FCM)';...
'K-means';'G-means'},'unit','norm','Position',[0.62 0.5 0.2 0.41],...
'HorizontalAlignment','left','ForegroundColor','b','FontSize',12,'Fontweight','bold','FontName',...
'Times New Roman');
uicontrol('parent',tab6,'style','text','string',{'Firing Rate (FR)';'Inter-Spike Intervals (ISI)';...
'Autocorrelogram'},'unit','norm','Position',[0.85 0.5 0.15 0.4],'Fontweight',...
'bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left','ForegroundColor','k');
end

 

