function spike_extraction_software
clc;clear;close all;
S.fig=figure('NumberTitle','off','Name','','MenuBar','none','ToolBar','none','Resize','off',...
'Color',0.94*[1 1 1],'Units','normalized','Position',[0.02 0.011 0.97 0.95]);
%% ====================================== Introduction =========================================
tg=uitabgroup;
tab1=uitab('parent',tg,'Title','<html><font family="Times New Roman" size=5 color="k"><b> Software Outline </font></html>');
S.start=uipanel('parent',tab1,'Title','','unit','norm','Position',[0 0 1 1],'Fontweight',...
'bold','FontSize',16,'FontName','Times New Roman');
S.text=uicontrol('parent',S.start,'style','text','string','Spike Extraction Software','unit','norm',...
'Position',[0.18 0.94 0.65 0.05],'Fontweight','bold','FontSize',20,'FontName','Times New Roman','FontAngle','italic');
S.text=uicontrol('parent',S.start,'style','text','string',...
{'We have developed a Spike Extraction Software (SES) based on a Graphical User Interface of MATLAB. The main purpose of the software is that'....
'provides a framework for evaluation of different methods and algorithms in single-channel extracellular recordings of neural activity. The features'...
'available in SES include identification of action potential templates, spike extraction, measurement of spike rates and various statistical tools such as'....
'measurement of inter-spike intervals and autocorrelogram histogram. The package currently contains six different steps:'},...
'unit','norm','Position',[0.08 0.8 0.85 0.13],'FontSize',14,'FontName','Times New Roman','HorizontalAlignment','left');
if exist('Image\BlockDiagram.jpg','file')~=0;a=axes('Parent',S.start,'unit','norm','position',[0.01 0.49 0.98 0.3]);
uistack(a,'bottom');X=imread('BlockDiagram.jpg');imagesc(X);a.Color=0.94*[1 1 1];a.XColor=0.94*[1 1 1];a.YColor=0.94*[1 1 1];
a.XTick=[];a.YTick=[];
end
if exist('Image\ListStep.jpg','file')~=0;b=axes('Parent',S.start,'unit','norm','position',[0.07 0 0.8 0.5]);
uistack(b,'bottom');X=imread('ListStep.jpg');imagesc(X);b.Color=0.94*[1 1 1];b.XColor=0.94*[1 1 1];b.YColor=0.94*[1 1 1];
b.XTick=[];b.YTick=[];
end
%% ==================================== Load Data ==============================================
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="red"><b> Load & Filtering</font></html>');
S.t1=uicontrol('parent',tab1,'style','text','string','Step 1','unit','norm',...
'Position',[0.005 0.965 0.37 0.037],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.65 0.65 0.65]);
S.L1=uipanel('parent',tab1,'Title','Load Data','unit','norm','Position',....
[0.005 0.415 0.37 0.55],'ShadowColor',[0.9290 0.6940 0.1250],'BorderWidth',...
2,'FontSize',12,'FontName','Times New Roman','Fontweight','bold');
S.L2=uipanel('parent',S.L1,'Title','','unit','norm','Position',...
[0.013 0.8 0.97 0.2],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.load=uicontrol('parent',S.L2,'style','pushbutton','string','Open File',...
'unit','norm','Position',[0.02 0.17 0.25 0.6],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Data Name:','unit',...
'norm','Position',[0.3 0.5 0.5 0.38],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.text1=uicontrol('parent',S.L2,'style','text','string','','unit','norm',...
'Position',[0.3 0.28 0.67 0.32],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','BackgroundColor',0.9*[1 1 1],'HorizontalAlignment','left',...
'ForegroundColor','r');
% Param
S.L2=uipanel('parent',S.L1,'Title','Set Parameters','unit','norm','Position',...
[0.013 0.25 0.97 0.55],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
% Clear all data
S.L3=uipanel('parent',S.L2,'Title','Clear Parameters','unit','norm','Position',...
[0.01 0.7 0.98 0.3],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.radio=uicontrol('parent',S.L3,'style','radio','string','Clear all Parameters & Figures',...
'unit','norm','Position',[0.008 0.21 0.51 0.85],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
% Input
S.L3=uipanel('parent',S.L2,'Title','Select Input:','unit','norm','Position',...
[0.01 0.35 0.98 0.35],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.inp=uicontrol('parent',S.L3,'style','popupmenu','string','Selection','unit','norm',...
'Position',[0.01 0.65 0.2971 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
% Normalize
S.L3=uipanel('parent',S.L2,'Title','Normalization','unit','norm','Position',...
[0.01 0.05 0.98 0.3],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.radio1=uicontrol('parent',S.L3,'style','radio','string','Active','unit',...
'norm','Position',[0.008 0.2 0.15 0.85],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
% Channel
S.L3=uipanel('parent',S.L1,'Title','Select Input Channels:','unit','norm','Position',...
[0.013 0.03 0.97 0.22],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.input=uicontrol('parent',S.L3,'style','popupmenu','string','Selection','unit',...
'norm','Position',[0.02 0 0.29 0.8],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.t1=uicontrol('parent',S.L3,'style','text','string','Chi:','unit','norm',...
'Position',[0.42 0.2 0.13 0.52],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Chi=uicontrol('parent',S.L3,'style','edit','string','','unit','norm','enable',...
'off','Position',[0.50 0.3 0.15 0.52],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','Tooltip','0<Chi<Num(All Ch)-1');
S.t1=uicontrol('parent',S.L3,'style','text','string','Chj:','unit','norm',...
'Position',[0.75 0.2 0.13 0.52],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Chj=uicontrol('parent',S.L3,'style','edit','string','','unit','norm','enable',...
'off','Position',[0.83 0.3 0.15 0.52],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','Tooltip','Chi<Chj<=Num(All Ch)');
%% ===================================== Filtering =============================================
S.t1=uicontrol('parent',tab1,'style','text','string','Step 2','unit',...
'norm','Position',[0.382 0.965 0.37 0.037],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.65 0.65 0.65]);
S.L1=uipanel('parent',tab1,'Title','Filtering','unit','norm','Position',...
[0.382 0.415 0.37 0.55],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'ShadowColor',[0.75, 0, 0.75],'BorderWidth',2);
S.L2=uipanel('parent',S.L1,'Title','Notch Filter ','unit','norm','Position',...
[0.013 0.845 0.97 0.15],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.notch=uicontrol('parent',S.L2,'style','radio','string','Active','unit',...
'norm','Position',[0.018 0.2 0.14 0.73],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
S.t1=uicontrol('parent',S.L2,'style','text','string','F0 (Hz):','unit',...
'norm','Position',[0.5 0.21 0.8 0.6],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
S.Fnotch=uicontrol('parent',S.L2,'style','edit','string','50','unit',...
'norm','Position',[0.7 0.2 0.2 0.8],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Design Method','unit','norm','Position',...
[0.013 0.67 0.49 0.17],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.design=uicontrol('parent',S.L2,'style','popupmenu','unit','norm','Fontweight',...
'bold','string',{'Selection';'Moving Average',;'Butter';'Cheby1';'Cheby2';'Ellip'},...
'Position',[0.04 0 0.8 0.9],'FontSize',11,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Response Type','unit','norm','Position',...
[0.51 0.67 0.475 0.17],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.response=uicontrol('parent',S.L2,'style','popupmenu','unit','norm','Fontweight',...
'bold','Position',[0.04 0 0.8 0.9],'FontSize',11,'FontName','Times New Roman',...
'string',{'Selection';'Lowpass';'Highpass';'Bandpass';'Bandstop'});
S.Parameters=uipanel('parent',S.L1,'Title','Set Parameters','unit','norm','Position',...
[0.013 0.195 0.97 0.47],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.Parameters,'style','text','string','Fs (Hz):','unit',...
'norm','Position',[0.023 0.81 0.65 0.11],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.fs=uicontrol('parent',S.Parameters,'style','edit','string','','unit','norm',...
'Position',[0.21 0.76 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Sampling Frequency');
S.t1=uicontrol('parent',S.Parameters,'style','text','string','Order:','unit',...
'norm','Position',[0.54 0.81 0.65 0.11],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.order=uicontrol('parent',S.Parameters,'style','edit','string','3','unit','norm',...
'Position',[0.75 0.76 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Order>0');
S.t1=uicontrol('parent',S.Parameters,'style','text','string','Fpass (Hz):','unit',...
'norm','Position',[0.023 0.498 0.65 0.12],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.fl=uicontrol('parent',S.Parameters,'style','edit','string','','unit','norm',...
'Position',[0.21 0.45 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Fpass>1');
S.t1=uicontrol('parent',S.Parameters,'style','text','string','Fstop (Hz):',...
'unit','norm','Position',[0.54 0.492 0.65 0.12],'Fontweight','bold','FontSize',...
11,'FontName','Times New Roman','HorizontalAlignment','left');
S.fh=uicontrol('parent',S.Parameters,'style','edit','string','','unit','norm',...
'Position',[0.75 0.45 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Fstop>1');
S.t1=uicontrol('parent',S.Parameters,'style','text','string','Rp (dB):','unit',...
'norm','Position',[0.023 0.15 0.65 0.12],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.rp=uicontrol('parent',S.Parameters,'style','edit','string','2','unit','norm',...
'Position',[0.21 0.11 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Rp>1');
S.t1=uicontrol('parent',S.Parameters,'style','text','string','Rs (dB):','unit',...
'norm','Position',[0.54 0.16 0.65 0.11],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.rs=uicontrol('parent',S.Parameters,'style','edit','string','3','unit','norm',...
'Position',[0.75 0.11 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Rs>1');
S.Window=uipanel('parent',S.L1,'Title','Parameter Moving Average','unit',...
'norm','Position',[0.013 0.03 0.55 0.17],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','BorderWidth',2);
S.t1=uicontrol('parent',S.Window,'style','text','string','Window Length:',...
'unit','norm','Position',[0.017 0.32 0.99 0.45],'Fontweight','bold','FontSize',...
11,'FontName','Times New Roman','HorizontalAlignment','left');
S.window=uicontrol('parent',S.Window,'style','edit','string','3','unit','norm',...
'Position',[0.6 0.18 0.35 0.73],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','Tooltip','Window size>1');
S.L2=uipanel('parent',S.L1,'Title','','unit','norm','Position',[0.57 0.03 0.413 0.147],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.checkFil=uicontrol('parent',S.L2,'style','check','string','Filtering Analysis',...
'unit','norm','Position',[0.02 0.15 0.72 0.73],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','Tooltip','Window size>1');
S.L1=uipanel('Parent',tab1,'Title','Plot & Save Data & Figures','unit','norm',...
'outerposition',[0.757 0.415 0.23 0.55],'ShadowColor',[0.4660 0.6740 0.1880],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.L2=uipanel('Parent',S.L1,'Title','Plot','unit','norm','position',[0.013 0.215 0.97 0.78],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.tabel=uitable(S.L2,'position',[6 145 260 102],'RowName',{'Sample';'Second';'Minute';'Hour'},...
'Data',{'';'';'';''},'ColumnName',{'Data Duration'},'ColumnWidth',{181 181 181},'FontSize',10);
S.t1=uicontrol('parent',S.L2,'style','text','string','Display Figure:','unit',...
'norm','Position',[0.025 0.33 0.5 0.15],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.display=uicontrol('parent',S.L2,'style','popupmenu','string',{'Selection';'Part of Data';...
'All Data'},'unit','norm','Position',[0.555 0.39 0.4 0.1],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment',...
'left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Select Time Type:','unit',...
'norm','Position',[0.025 0.165 0.49 0.15],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.time=uicontrol('parent',S.L2,'style','popupmenu','string',{'Sample';'Second';'Minute';...
'Hour'},'unit','norm','Position',[0.555 0.23 0.4 0.1],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Custom range:','unit','norm',....
'Position',[0.025 0.023 0.5 0.12],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.time1=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.38 0.05 0.27 0.12],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','to','unit','norm','Position',...
[0.655 0.023 0.07 0.12],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.time2=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.72 0.05 0.27 0.12],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.L2=uipanel('Parent',S.L1,'Title','Save Results','unit','norm','position',...
[0.013 0.03 0.97 0.18],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.saveresult=uicontrol('parent',S.L2,'style','check','string','Save Filtered Signal',...
'unit','norm','Position',[0.025 0.3 0.535 0.38],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.L1=uipanel('Parent',tab1,'Title','Figure Raw & Filtered Signals','unit','norm',...
'outerposition',[0.005 0 0.991 0.41],'ShadowColor','b','Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','BorderWidth',2);
S.ax(1)=axes('Parent',S.L1,'unit','norm','position',[0.05 0.59 0.9 0.37],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman','XTick',[]);
S.ax(2)=axes('Parent',S.L1,'unit','norm','position',[0.05 0.16 0.9 0.37],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
%% ======================================= Detect Spike ========================================
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="green"><b>Spike Detection</font></html>');
S.t1=uicontrol('parent',tab1,'style','text','string','Step 3','unit','norm',...
'Position',[0.3 0.965 0.4 0.037],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.65 0.65 0.65]);
S.L1=uipanel('parent',tab1,'Title','Select Input & Parameters','unit','norm',...
'Position',[0.005 0.645 0.991 0.32],'ShadowColor',[0.6350 0.0780 0.1840],'Fontweight',...
'bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.L2=uipanel('parent',S.L1,'Title','Select Input','unit','norm','Position',...
[0.005 0.5 0.182 0.48],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.inputs=uibuttongroup('parent',S.L2,'Title','','BorderType','none','unit','norm',...
'pos',[0.013 0.03 0.99 0.95]);
S.rawS=uicontrol('parent',S.inputs,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Raw Signal', 'unit','norm',...
'pos',[0.013 .7 .5 .22]);S.rawS.Value=false;
S.filterS=uicontrol('parent',S.inputs,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Flitered Signal', 'unit',...
'norm', 'pos',[0.013 .4 .52 .22]);
S.derivS=uicontrol('parent',S.inputs,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','1st Derivative of Flitered Data',...
'unit','norm','pos',[0.013 .08 .99 .22]);align([S.rawS,S.filterS,S.derivS],'left','Fixed',7);
S.L2=uipanel('parent',S.L1,'Title','Detection Type','unit','norm','Position',...
[0.005 0.03 0.182 0.48],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.detec=uibuttongroup('parent',S.L2, 'Title','','BorderType','none','unit','norm',...
'pos',[0.013 0.03 0.99 0.95]);
S.ppeak=uicontrol('parent',S.detec,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Positive peaks','unit','norm',...
'pos',[0.013 .7 .52 .22]);
S.npeak=uicontrol('parent',S.detec,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Negative peaks', 'unit',...
'norm', 'pos',[0.013 .4 .54 .22]);
S.bpeak=uicontrol('parent',S.detec,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Both peaks','unit','norm',...
'pos',[0.013 .08 .42 .22]);align([S.ppeak,S.npeak,S.bpeak],'left','Fixed',7);
S.L2=uipanel('parent',S.L1,'Title','Set Threshold','unit','norm','Position',....
[0.19 0.04 0.18 0.941],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.thresh=uibuttongroup('parent',S.L2, 'Title','','unit','norm','pos',[0.013 0.77 0.99 0.2]);
S.plotmanual=uicontrol('parent',S.thresh,'style','radiobutton','Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman','string','Manual',...
'unit','norm','pos',[0.013 .2 .5 .5]);S.plotmanual.Value=false;
S.plotauto=uicontrol('parent',S.thresh,'style','radiobutton','Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman','string','Automatic',...
'unit','norm','pos',[0.55 .2 .5 .5]);align([S.plotmanual,S.plotauto],'Distribute','Middle');
S.t1=uicontrol('parent',S.L2,'style','text','string','Thr_min {+}:','unit','norm',...
'Position',[0.015 0.51 0.45 0.19],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.thrmi=uicontrol('parent',S.L2,'style','edit','string','','unit','norm',...
'Position',[0.56 0.55 0.4 0.18],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Thr_min {-}:',...
'unit','norm','Position',[0.015 0.25 0.45 0.19],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.thrmineg=uicontrol('parent',S.L2,'style','edit','string','','unit','norm',...
'Position',[0.56 0.3 0.4 0.18],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','enable','off');
S.t1=uicontrol('parent',S.L2,'style','text','string','Thr_max {+&-}:',...
'unit','norm','Position',[0.015 0.02 0.55 0.19],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.thrma=uicontrol('parent',S.L2,'style','edit','string','','unit','norm',...
'Position',[0.56 0.06 0.4 0.18],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Set Events','unit','norm','Position',[0.373 0.04 0.45 0.941],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman','BorderWidth',2);
S.L3=uipanel('parent',S.L2,'Title','','unit','norm','Position',[0.005 0.27 0.49 0.7],...
'BorderWidth',1);
S.t1=uicontrol('parent',S.L3,'style','text','string','Number Pre-Event {+}:',...
'unit','norm','Position',[0.015 0.61 0.6 0.19],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.pre=uicontrol('parent',S.L3,'style','edit','string','20','unit','norm',...
'Position',[0.62 0.57 0.35 0.28],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.t1=uicontrol('parent',S.L3,'style','text','string','Number Post-Event {+}:',...
'unit','norm','Position',[0.015 0.12 0.6 0.19],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.pos=uicontrol('parent',S.L3,'style','edit','string','40','unit','norm',...
'Position',[0.62 0.1 0.35 0.28],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.L3=uipanel('parent',S.L2,'Title','','unit','norm','Position',[0.504 0.27 0.49 0.7],...
'BorderWidth',1);
S.t1=uicontrol('parent',S.L3,'style','text','string','Number Pre-Event {-}:',...
'unit','norm','Position',[0.015 0.61 0.6 0.19],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.pren=uicontrol('parent',S.L3,'style','edit','string','20','unit','norm',...
'Position',[0.62 0.57 0.35 0.28],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','enable','off');
S.t1=uicontrol('parent',S.L3,'style','text','string','Number Post-Event {-}:',...
'unit','norm','Position',[0.015 0.12 0.6 0.19],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.posn=uicontrol('parent',S.L3,'style','edit','string','40','unit','norm',...
'Position',[0.62 0.1 0.35 0.28],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','enable','off');
S.t1=uicontrol('parent',S.L2,'style','text','string','Dead Time:',...
'unit','norm','Position',[0.015 0.07 0.6 0.1],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.alig=uicontrol('parent',S.L2,'style','edit','string','50','unit','norm',...
'Position',[0.305 0.03 0.17 0.18],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.Exec=uicontrol('parent',S.L2,'style','check','string','Spike Detection Analysis',...
'unit','norm','Position',[0.505 0.07 0.32 0.1],'Fontweight','bold','FontSize',...
11,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Plot','unit','norm','Position',[0.825 0.04 0.17 0.941],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Display Figure:','unit','norm',...
'Position',[0.013 0.75 0.6 0.2],'Fontweight','bold','FontSize',10.7,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.time3=uicontrol('parent',S.L2,'style','popupmenu','string',{'Part of Data';'All Data';},...
'unit','norm','Position',[0.478 0.57 0.49 0.4],'Fontweight','bold','FontSize',...
11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Time:','unit','norm',...
'Position',[0.013 0.54 0.25 0.2],'Fontweight','bold','FontSize',10.7,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.time4=uicontrol('parent',S.L2,'style','popupmenu','string',{'Sample';'Second';'Minute'},...
'unit','norm','Position',[0.478 0.37 0.49 0.4],'Fontweight','bold','FontSize',10.7,...
'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Custom range:','unit',...
'norm','Position',[0.013 0.35 0.5 0.2],'Fontweight','bold','FontSize',10.7,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.time5=uicontrol('parent',S.L2,'style','edit','string','','unit','norm',...
'Position',[0.013 0.25 0.35 0.16],'Fontweight','bold','FontSize',10.7,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','to','unit','norm','Position',...
[0.4 0.19 0.09 0.2],'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.time6=uicontrol('parent',S.L2,'style','edit','string','','unit',...
'norm','Position',[0.5 0.25 0.35 0.16],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Width_axis:','unit','norm',...
'Position',[0.013 0.06 0.4 0.1],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.waw=uicontrol('parent',S.L2,'style','edit','string','1000','unit','norm','Position',...
[0.5 0.03 0.35 0.16],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
tabgp=uitabgroup(tab1,'Position',[0.005 0 0.991 0.65]);
tab1 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="#800080"><b>Waveform Detection</font></html>');
S.L1=uipanel('Parent',tab1,'Title','','unit','norm','position',...
[0 0 1 1],'ShadowColor','m','BorderWidth',2);
S.slid1=uicontrol(S.L1,'style','slider','units','norm','position',[0.07103,0.01,0.91,0.035],...
'BackgroundColor',[255,165,0]/255);
S.ax(3)=axes('Parent',S.L1,'unit','norm','position',[0.07 0.69 0.91 0.3],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman','XTick',[]);
S.ax(4)=axes('Parent',S.L1,'unit','norm','position',[0.07 0.6025 0.91 0.08],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman','XTick',[],'YTick',[]);
S.ax(5)=axes('Parent',S.L1,'unit','norm','position',[0.07 0.17 0.91 0.43],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.slid2=uicontrol(S.L1,'style','slider','units','norm','position',[0.02,0.135,0.01,0.495],...
'BackgroundColor','r');
tab1 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="#008080"><b>Spike Waveforms & Phase Space</font></html>');
S.L1=uipanel('Parent',tab1,'Title','','unit','norm','position',[0 0 1 1],'ShadowColor',...
[0,128,128]/255,'BorderWidth',2);
S.L2=uipanel('parent',S.L1,'Title','Plot & Save Results','ShadowColor',[255,193,37]/255,...
'unit','norm','Position',[0.005 0.02 0.25 0.96],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','BorderWidth',2);
S.L3=uipanel('parent',S.L2,'Title','Plot','unit','norm','Position',[0.013 0.71 0.97 0.27],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.dspikeven=uicontrol('parent',S.L3,'style','check','string','Display Spike Waveforms','unit',...
'norm','Position',[0.015 0.65 0.625 0.23],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.dphaspace=uicontrol('parent',S.L3,'style','check','string','Display Phase space','unit',...
'norm','Position',[0.015 0.2 0.53 0.23],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.L2=uipanel('parent',S.L2,'Title','Save','unit','norm','Position',[0.013 0.34 0.97 0.35],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.sevent=uicontrol('parent',S.L2,'style','check','string','Save Event Results','unit',...
'norm','Position',[0.015 0.67 0.5 0.23],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.sspike=uicontrol('parent',S.L2,'style','check','string','Save Spike Waveform Results','unit',...
'norm','Position',[0.015 0.38 0.725 0.23],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.sphase=uicontrol('parent',S.L2,'style','check','string','Save Phase space Results','unit',...
'norm','Position',[0.015 0.1 0.63 0.23],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.tabe2=uitable(S.L1,'position',[15 50 304 82],'RowName',{'sigma';'Thershold';'Total Spikes'},...
'Data',{'';'';''},'ColumnName',{'Values'},'ColumnWidth',{170 170 170},'FontSize',10);
S.L2=uipanel('parent',S.L1,'Title','Figure Spike Waveforms','ShadowColor',[127,255,0]/255,...
'unit','norm','Position',[0.26 0.02 0.365 0.96],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','BorderWidth',2);
S.ax(6)=axes('Parent',S.L2,'unit','norm','position',[0.12 0.12 0.85 0.8],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Figure Phase Space','ShadowColor',[220,20,60]/255,...
'unit','norm','Position',[0.63 0.02 0.365 0.96],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','BorderWidth',2);
S.ax(7)=axes('Parent',S.L2,'unit','norm','position',[0.12 0.12 0.85 0.8],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
%% ================================ Feature Extraction =========================================
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="blue"><b> Feature Extraction</font></html>');
S.t1=uicontrol('parent',tab1,'style','text','string','Step 4','unit','norm',...
'Position',[0.3 0.965 0.4 0.037],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.65 0.65 0.65]);
S.L1=uipanel('parent',tab1,'Title','Select Feature & Parameters','unit','norm',...
'Position',[0.005 0.615 0.991 0.35],'ShadowColor',[238,18,137]/255,'FontSize',12,...
'FontName','Times New Roman','BorderWidth',2,'Fontweight','bold');
S.L2=uipanel('parent',S.L1,'Title','PCA','unit','norm','Position',[0.005 0.05 0.15 0.95],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.Tikpca=uicontrol('parent',S.L2,'style','check','string','Active PCA','unit','norm',...
'Position',[0.013 0.765 0.53 0.3],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Feature 1:','unit','norm',...
'Position',[0.02 0.59 0.38 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Feat1=uicontrol('parent',S.L2,'style','edit','string','1','unit','norm','Position',...
[0.525 0.66 0.43 0.15],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Feature 2:','unit','norm',...
'Position',[0.02 0.38 0.38 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Feat2=uicontrol('parent',S.L2,'style','edit','string','2','unit','norm','Position',...
[0.525 0.45 0.43 0.15],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Feature 3:','unit','norm',...
'Position',[0.02 0.15 0.38 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Feat3=uicontrol('parent',S.L2,'style','edit','string','3','unit','norm','Position',...
[0.525 0.24 0.43 0.15],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.dispca=uicontrol('parent',S.L2,'style','check','string','PCA Analysis & Plot','unit',...
'norm','Position',[0.02 0.008 0.85 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Wavelet Parameters','unit','norm','Position',...
[0.16 0.05 0.32 0.95],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.Tikwavelet=uicontrol('parent',S.L2,'style','check','string','Active Wavelet','unit',...
'norm','Position',[0.013 0.76 0.34 0.3],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.L3=uipanel('parent',S.L2,'Title','','unit','norm','Position',...
[0.005 0.535 0.99 0.28],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.L3,'style','text','string','Wavelet:','unit','norm',...
'Position',[0.02 0.38 0.38 0.3],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.wave=uicontrol('parent',S.L3,'style','popupmenu','string',{'haar';'db2';'db3';...
'db4';'db5';'db6';'db7';'db8';'db9';'db10';'coif1';'coif2';'coif3';'coif4';'coif5';...
'sym2';'sym3';'sym4';'sym5';'fk4';'fk6';'fk8';'fk14';'fk22';'bior1.1';'bior1.3';...
'bior1.5';'bior2.2';'bior2.4';'bior2.6';'rbio1.1';'rbio1.3';'rbio1.5';'rbio2.2';...
'rbio2.4';'rbio2.6';'rbio2.8'},'unit','norm','Position',[0.24 0.57 0.21 0.19],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L3,'style','text','string','Level:','unit','norm',...
'Position',[0.53 0.38 0.38 0.3],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.leve=uicontrol('parent',S.L3,'style','popupmenu','string',{'1';'2';'3';'4';'5';...
'6';'7';'8';'9';'10';'11';'12';'13';'15'},'unit','norm','Position',...
[0.75 0.57 0.21 0.19],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L2,'Title','','unit','norm','Position',...
[0.005 0.01 0.99 0.52],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Feature 1:','unit','norm',...
'Position',[0.02 0.655 0.38 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Feat31=uicontrol('parent',S.L2,'style','edit','string','1','unit','norm','Position',...
[0.24 0.6 0.21 0.32],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Feature 2:','unit','norm',...
'Position',[0.53 0.65 0.38 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Feat32=uicontrol('parent',S.L2,'style','edit','string','2','unit','norm',...
'Position',[0.75 0.6 0.21 0.32],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Feature 3:','unit',...
'norm','Position',[0.02 0.155 0.38 0.17],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.Feat33=uicontrol('parent',S.L2,'style','edit','string','3','unit','norm',...
'Position',[0.24 0.08 0.21 0.32],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.diswave=uicontrol('parent',S.L2,'style','check','string','Wavelet Analysis & Plot',...
'unit','norm','Position',[0.52 0.13 0.455 0.17],'Fontweight','bold','FontSize',...
11,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Plot','unit','norm','Position',[0.485 0.595 0.15 0.4],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.Plot=uibuttongroup('parent',S.L2,'Title','','unit','norm','pos',[0 0 1 1],...
'BorderType','none');
S.plot2D=uicontrol('parent',S.Plot,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Plot 2 Dimensional','unit',...
'norm','pos',[0.013 .43 .78 .4]);
S.plot3D=uicontrol('parent',S.Plot,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Plot 3 Dimensional','unit',...
'norm','pos',[0.013 .1 .78 .4]);align([S.plot2D,S.plot3D],'left','Fixed',4);
S.L2=uipanel('parent',S.L1,'Title','Save Results','unit','norm','Fontweight','bold',...
'Position',[0.485 0.18 0.15 0.4],'FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.spca=uicontrol('parent',S.L2,'style','check','string','Save PCA Features','unit',...
'norm','Position',[0.015 0.6 0.79 0.23],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.swavelet=uicontrol('parent',S.L2,'style','check','string','Save Wavelet Feature','unit',...
'norm','Position',[0.015 0.12 0.88 0.23],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.L1=uipanel('Parent',tab1,'Title','Plot Input Space','unit','norm','Position',...
[0.005 0 0.35 0.615],'ShadowColor',[199,97,20]/255,'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','BorderWidth',2);
S.ax(8)=axes('Parent',S.L1,'unit','norm','position',[0.12 0.5 0.85 0.46],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.ax(9)=axes('Parent',S.L1,'unit','norm','position',[0.12 0.05 0.85 0.35],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.L1=uipanel('Parent',tab1,'Title','Plot Output Space (Projection)','unit','norm','OuterPosition',...
[0.36 0 0.35 0.615],'ShadowColor',[135,38,87]/255,'Fontweight','bold','FontSize',...
12,'FontName','Times New Roman','BorderWidth',2);
S.ax(10)=axes('Parent',S.L1,'unit','norm','position',[0.12 0.5 0.85 0.46],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.ax(11)=axes('Parent',S.L1,'unit','norm','position',[0.12 0.05 0.85 0.35],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
%% =================================== Clustering ==============================================
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="#C76114"><b> Clustering</font></html>');
S.t1=uicontrol('parent',tab1,'style','text','string','Step 5','unit','norm',...
'Position',[0.3 0.965 0.4 0.037],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.65 0.65 0.65]);
S.L1=uipanel('parent',tab1,'Title','Select Cluster & Parameters','unit','norm',...
'Position',[0.005 0.745 0.991 0.22],'ShadowColor',[205,205,0]/255,'FontSize',12,'FontName',...
'Times New Roman','BorderWidth',2,'Fontweight','bold');
S.L2=uipanel('parent',S.L1,'Title','Input','unit','norm','Position',[0.005 0.05 0.15 0.95],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.inpclust=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Input Type';...
'PCA Features';'Wavelet Features'},'unit','norm','Position',[0.009 0.68 0.88 0.19],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.plotc=uicontrol('parent',S.L2,'style','check','string','Display Cluster Input',...
'unit','norm','Position',[0.009 0.07 0.88 0.3],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','HorizontalAlignment','left', 'Value', 1);
S.L2=uipanel('parent',S.L1,'Title','Cluster Parameters','unit','norm','Position',...
[0.157 0.05 0.4 0.95],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.L3=uipanel('parent',S.L2,'Title','','unit','norm','Position',[0.005 0.6 0.39 0.31],...
'BorderType','none');
S.center=uibuttongroup('parent',S.L3, 'Title','','unit','norm','pos',[0 0 1 1]);
S.manual=uicontrol('parent',S.center,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Manual','unit','norm','pos',...
[0.009 .2 .5 .5]);S.manual.Value=false;
S.auto=uicontrol('parent',S.center,'style','radiobutton','Fontweight','bold','FontSize',...
11,'FontName','Times New Roman','string','Automatic','unit','norm','pos',[0.55 .2 .5 .5]);
align([S.manual,S.auto],'Distribute','Middle');
S.cursor=uicontrol('parent',S.L2,'style','check','string','Enable Cursor Mode',...
'unit','norm','Position',[0.01 0.07 0.323 0.3],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','HorizontalAlignment','left', 'Value', 1);
S.t1=uicontrol('parent',S.L2,'style','text','string','Select Cluster Type:','unit',...
'norm','Position',[0.45 0.48 0.7 0.33],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.clus=uicontrol('parent',S.L2,'style','popupmenu','string',{'FCM';'K-means'},'unit','norm', ...
'Position',[0.75 0.495 0.22 0.35],'Fontweight','bold','FontSize',12,'FontName','Times New Roman', ...
'HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Number Cluster:','unit',...
'norm','Position',[0.45 0.09 0.7 0.2],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.numcl=uicontrol('parent',S.L2,'style','popupmenu','string',{'Selection';'1';'2';'3';...
'4';'5';'6';'7';'8';'9';'10';'11';'12';'13';'14'},'unit','norm','Position',[0.75 0.14 0.22 0.2],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Plot','unit','norm','Position',...
[0.56 0.05 0.437 0.95],'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.plotR=uicontrol('parent',S.L2,'style','popupmenu','string',{'Selection';'Display Raster Per Sample';...
'Display Raster Per Second';'Display Raster Per Minute';'Display Raster Per Hour'},'unit',...
'norm','Position',[0.017 0.62 0.4 0.3],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.plotSU=uicontrol('parent',S.L2,'style','check','string','Display Clustered Spike Waveforms',...
'unit','norm','Position',[0.017 0.35 0.7 0.3],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.plotPhU=uicontrol('parent',S.L2,'style','check','string','Display Clustered Phase Spaces',...
'unit','norm','Position',[0.017 0.07 0.7 0.3],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.sraster=uicontrol('parent',S.L2,'style','check','string','Save Raster Results','unit',...
'norm','Position',[0.485 0.62 0.3 0.33],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.sspikeuint=uicontrol('parent',S.L2,'style','check','string','Save Clustered Spike waveform Results',...
'unit','norm','Position',[0.485 0.35 0.52 0.3],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.sphaseuint=uicontrol('parent',S.L2,'style','check','string','Save Clustered Phase Space Results',...
'unit','norm','Position',[0.485 0.07 0.51 0.3],'Fontweight','bold','FontSize',12,...
'FontName','Times New Roman','HorizontalAlignment','left');
tabgp=uitabgroup(tab1,'Position',[0.005 0 0.992 0.746]);
tab1 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="#B452CD"><b>Clustering & Raster Figures</font></html>');
S.L1=uipanel('Parent',tab1,'Title','','unit','norm','position',[0 0 1 1],'ShadowColor',...
[180,82,205]/255,'BorderWidth',2);
S.L2=uipanel('Parent',S.L1,'Title','Feature Extraction Figure','unit','norm',...
'position',[0.005 0.3 0.48 0.7],'ShadowColor',[0,0,128]/255,'Fontweight',...
'bold','FontSize',13,'FontName','Times New Roman','BorderWidth',2);
S.ax(12)=axes('Parent',S.L2,'unit','norm','position',[0.12 0.16 0.8 0.78],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.L2=uipanel('Parent',S.L1,'Title','Clustering Figure','unit','norm','position',...
[0.515 0.3 0.48 0.7],'ShadowColor',[227,168,105]/255,'Fontweight','bold',...
'FontSize',13,'FontName','Times New Roman','BorderWidth',2);
S.ax(13)=axes('Parent',S.L2,'unit','norm','position',[0.12 0.16 0.8 0.78],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.L2=uipanel('Parent',S.L1,'Title','Raster Figure','unit','norm','position',...
[0.005 0 0.99 0.3],'ShadowColor',[0,250,154]/255,'Fontweight','bold',...
'FontSize',13,'FontName','Times New Roman','BorderWidth',2);
S.ax(14)=axes('Parent',S.L2,'unit','norm','position',[0.05 0.36 0.9 0.6],'box',...
'on','Fontweight','bold','FontSize',10,'FontName','Times New Roman');
tab1 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="#CD0000"><b>Clustered Spike waveform & Phase Sapce Figures</font></html>');
S.L1=uipanel('Parent',tab1,'Title','','unit','norm','position',[0 0 1 1],'ShadowColor',...
[205,0,0]/255,'BorderWidth',2);
S.L2=uipanel('Parent',S.L1,'Title','Clustered Spike Waveforms Figure','unit','norm',...
'position',[0.005 0.01 0.48 0.987],'ShadowColor',[238,238,0]/255,'Fontweight',...
'bold','FontSize',13,'FontName','Times New Roman','BorderWidth',2);
S.ax(15)=axes('Parent',S.L2,'unit','norm','position',[0.12 0.1 0.85 0.88],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.L2=uipanel('Parent',S.L1,'Title','Clustered Phase Spaces Figure','unit','norm',...
'position',[0.515 0.01 0.48 0.987],'ShadowColor',[255,62,150]/255,'Fontweight',...
'bold','FontSize',13,'FontName','Times New Roman','BorderWidth',2);
S.ax(16)=axes('Parent',S.L2,'unit','norm','position',[0.12 0.1 0.85 0.88],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
tab1=uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="#00868B"><b>Spike Sorting Waveforms</font></html>');
S.L1=uipanel('Parent',tab1,'Title','','unit','norm','position',[0 0 1 1],'ShadowColor',...
[0,134,139]/255,'BorderWidth',2);
S.slid3=uicontrol(S.L1,'style','slider','units','norm','position',[0.07103,0.01,0.91,0.035],...
'BackgroundColor',[0,238,118]/255);
S.ax(17)=axes('Parent',S.L1,'unit','norm','position',[0.07 0.46 0.91 0.3],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman','XTick',[]);
S.ax(18)=axes('Parent',S.L1,'unit','norm','position',[0.07 0.15 0.91 0.3],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.L2=uipanel('Parent',S.L1,'Title','Plot','unit','norm','position',[0.07 0.76 0.54 0.25],...
'Fontweight','bold','FontSize',13,'FontName','Times New Roman','BorderWidth',2);
S.plotspikesort=uibuttongroup('parent',S.L2, 'Title','','unit','norm','pos',[0.009 0.05 0.18 0.95],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.sample=uicontrol('parent',S.plotspikesort,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Sample','unit','norm','pos',...
[0.009 .73 .55 .2]);S.sample.Value=false;
S.second=uicontrol('parent',S.plotspikesort,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Second','unit','norm','pos',...
[0.009 .49 .55 .2]);
S.minute=uicontrol('parent',S.plotspikesort,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Minute','unit','norm','pos',...
[0.009 .27 .57 .2]);
S.hour=uicontrol('parent',S.plotspikesort,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Hour','unit','norm','pos',...
[0.009 .03 .55 .2]);align([S.sample,S.second,S.minute,S.hour],'left','Fixed',3);
S.L3=uipanel('Parent',S.L2,'Title','','unit','norm','position',[0.2 0.05 0.42 0.95],...
'Fontweight','bold','FontSize',13,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L3,'style','text','string','Custom range:','unit',...
'norm','Position',[0.009 0.6 0.5 0.2],'Fontweight','bold','FontSize',10.7,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.time7=uicontrol('parent',S.L3,'style','edit','string','','unit','norm',...
'Position',[0.35 0.54 0.26 0.32],'Fontweight','bold','FontSize',10.7,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L3,'style','text','string','to','unit','norm','Position',...
[0.63 0.6 0.09 0.2],'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.time8=uicontrol('parent',S.L3,'style','edit','string','','unit',...
'norm','Position',[0.7 0.54 0.26 0.32],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L3,'style','text','string','Width_axis:','unit','norm',...
'Position',[0.009 0.06 0.4 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Xlim=uicontrol('parent',S.L3,'style','edit','string','1000','unit','norm','Position',...
[0.35 0.03 0.26 0.32],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.tabe3=uitable(S.L2,'position',[437 10 249 82],'RowName',{'Class 1';'Class 2';'Class 3'},...
'Data',{},'ColumnName',{'# Selected Spikes';'# Total Spikes'},'ColumnWidth','auto','FontSize',10);
%% ====================== Firing Rat & ISI & Autocorrelogram ==============
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="#800080"><b>Firing Rate & ISI & Autocorrelogram</font></html>');
S.t1=uicontrol('parent',tab1,'style','text','string','Step 6','unit','norm',...
'Position',[0.3 0.965 0.4 0.037],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.65 0.65 0.65]);
S.L1=uipanel('parent',tab1,'Title','Firing Rate & ISI & Autocorrelogram','unit','norm',...
'Position',[0.005 0.765 0.991 0.2],'ShadowColor',[0.4940 0.1840 0.5560],'FontSize',12,...
'FontName','Times New Roman','BorderWidth',2,'Fontweight','bold');
S.L2=uipanel('parent',S.L1,'Title','Firing Rate Parameters','unit','norm','Position',...
[0.005 0.05 0.38 0.95],'FontSize',12,'FontName','Times New Roman','Fontweight','bold',...
'BorderWidth',2);
S.binTime=uicontrol('parent',S.L2,'style','text','string','Bin(Sec)',...
'unit','norm','Position',[0.017 0.59 0.2 0.25],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
% S.binTime=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select:'; 'Bin(Sec)';'Bin(Min)';'Bin(Hour)'},...
% 'unit','norm','Position',[0.017 0.59 0.2 0.25],'Fontweight','bold','FontSize',11,'FontName',...
% 'Times New Roman','HorizontalAlignment','left');
S.binFR=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.25 0.55 0.18 0.3],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'Tooltip','e.g., 2 Sec');
S.sfringrate=uicontrol('parent',S.L2,'style','check','string','Save Firing Rate Results',...
'unit','norm','Position',[0.017 0.13 0.38 0.25],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.plotFR=uibuttongroup('parent',S.L2, 'Title','Plot','unit','norm','pos',[0.455 0.05 0.53 0.95],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.spikepersec=uicontrol('parent',S.plotFR,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Display Firing Rate (Spikes/Sec)',...
'unit','norm','pos',[0.009 .7 .92 .25]);S.spikepersec.Value=false;
S.countperbin=uicontrol('parent',S.plotFR,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Display Firing Rate (Counts/bin)',...
'unit','norm','pos',[0.009 .15 .92 .25]);
S.L2=uipanel('parent',S.L1,'Title','ISI & Autocorrelogram Parameters','unit',...
'norm','Position',[0.39 0.04 0.605 0.97],'FontSize',12,'FontName','Times New Roman',...
'Fontweight','bold','BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Min_Interval (Sec):',...
'unit','norm','Position',[0.013 0.68 0.25 0.25],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Max_Interval (Sec):',...
'unit','norm','Position',[0.013 0.35 0.25 0.25],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Bin (Sec):','unit',...
'norm','Position',[0.013 0.02 0.3 0.25],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.minInte=uicontrol('parent',S.L2,'style','edit','string','0','unit','norm',...
'Position',[0.28 0.66 0.14 0.3],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','e.g., 0 Sec');
S.maxnInte=uicontrol('parent',S.L2,'style','edit','string','','unit','norm',...
'Position',[0.28 0.335 0.14 0.3],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','e.g., 0.3 Sec');
S.bin=uicontrol('parent',S.L2,'style','edit','string','0.0005','unit','norm',...
'Position',[0.28 0.02 0.14 0.3],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','e.g., 0.0005 Sec');
S.L2=uipanel('parent',S.L2,'Title','Plot & Save Results','unit','norm','Position',...
[0.44 0.03 0.55 1.02],'FontSize',12,'FontName','Times New Roman','Fontweight','bold');
S.plotISI=uicontrol('parent',S.L2,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Display ISI','unit','norm','pos',...
[0.009 .7 .6 .25]);
S.sISI=uicontrol('parent',S.L2,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Save ISI Results','unit','norm','pos',...
[0.009 .12 .7 .25]);
S.plotautogram=uicontrol('parent',S.L2,'style','radiobutton','Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','string','Display Autocorrelogram',...
'unit','norm','pos',[0.46 .7 .6 .25]);
S.sautogram=uicontrol('parent',S.L2,'style','radiobutton','Fontweight','bold','FontSize',...
11,'FontName','Times New Roman','string','Save Autocorrelogram Results','unit','norm','pos',...
[0.46 .12 .7 .25]);
tabgp=uitabgroup(tab1,'Position',[0.005 0 0.992 0.765]);
tab1 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="#FFA500"><b>Firing Rate Figures</font></html>');
S.L1=uipanel('Parent',tab1,'Title','','unit','norm','position',[0 0 1 1],'ShadowColor',...
[255,165,0]/255,'BorderWidth',2);
S.L2=uipanel('Parent',tab1,'Title','Firing Rate All Units Figure','unit','norm','position',...
[0.009 0.02 0.49 0.96],'ShadowColor','g','Fontweight','bold','FontSize',11.5,'FontName',...
'Times New Roman','BorderWidth',2);
S.ax(19)=axes('Parent',S.L2,'unit','norm','position',[0.1 0.2 0.88 0.6],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.ax(20)=uipanel('Parent',tab1,'Title','Firing Rate Single Uint Figure','unit','norm',...
'position',[0.503 0.02 0.49 0.96],'ShadowColor','b','Fontweight','bold','FontSize',11.5,...
'FontName','Times New Roman','BorderWidth',2);
tab1 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="#DC143C"><b>ISI Figures</font></html>');
S.L1=uipanel('Parent',tab1,'Title','','unit','norm','position',[0 0 1 1],'ShadowColor',...
[220,20,60]/255,'BorderWidth',2);
S.L2=uipanel('Parent',tab1,'Title','ISI All Units Figure','unit','norm','position',...
[0.009 0.02 0.49 0.96],'ShadowColor','m','Fontweight','bold','FontSize',11.5,'FontName',...
'Times New Roman','BorderWidth',2);
S.ax(21)=axes('Parent',S.L2,'unit','norm','position',[0.1 0.2 0.88 0.6],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.ax(22)=uipanel('Parent',tab1,'Title','ISI Single Uint Figure','unit','norm',...
'position',[0.503 0.02 0.49 0.96],'ShadowColor','c','Fontweight','bold','FontSize',11.5,...
'FontName','Times New Roman','BorderWidth',2);
tab1 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="#B452CD"><b>Autocorrelogram Figures</font></html>');
S.L1=uipanel('Parent',tab1,'Title','','unit','norm','position',[0 0 1 1],'ShadowColor',...
[180,82,205]/255,'BorderWidth',2);
S.L2=uipanel('Parent',tab1,'Title','Autocorrelogram All Units Figure','unit','norm','position',...
[0.009 0.02 0.49 0.96],'ShadowColor',[227,168,105]/255,'Fontweight','bold','FontSize',11.5,'FontName',...
'Times New Roman','BorderWidth',2);
S.ax(23)=axes('Parent',S.L2,'unit','norm','position',[0.1 0.2 0.88 0.6],'box','on',...
'Fontweight','bold','FontSize',10,'FontName','Times New Roman');
S.ax(24)=uipanel('Parent',tab1,'Title','Autocorrelogram Single Uint Figure','unit','norm',...
'position',[0.503 0.02 0.49 0.96],'ShadowColor',[128,128,0]/255,'Fontweight','bold','FontSize',11.5,...
'FontName','Times New Roman','BorderWidth',2);
%% =========================== uicontextmenu   ============================
cm=uicontextmenu;uimenu('parent',cm,'label','Save','callback',@Save);
uimenu('parent',cm,'label','New Figure','callback',@NewFigure);
uimenu('parent',cm,'label','Subplot','callback',@Subplot);
CM=uicontextmenu;C1=uimenu('parent',CM,'label','Color');uimenu('parent',C1,'label','r','callback',@Color);
uimenu('parent',C1,'label','b','callback',@Color);uimenu('parent',C1,'label','g','callback',@Color);
uimenu('parent',C1,'label','k','callback',@Color);uimenu('parent',C1,'label','m','callback',@Color);
uimenu('parent',C1,'label','c','callback',@Color);uimenu('parent',C1,'label','y','callback',@Color);
CC=uimenu('parent',CM,'label','Linestyle');uimenu('parent',CC,'label','-','callback',@Linestyle);
uimenu('parent',CC,'label','--','callback',@Linestyle);uimenu('parent',CC,'label','-.','callback',@Linestyle);
uimenu('parent',CC,'label',':','callback',@Linestyle);CCC=uimenu('parent',CM,'label','Marker');
uimenu('parent',CCC,'label','none','callback',@Marker);uimenu('parent',CCC,'label','o','callback',@Marker);
uimenu('parent',CCC,'label','+','callback',@Marker);uimenu('parent',CCC,'label','*','callback',@Marker);
uimenu('parent',CCC,'label','.','callback',@Marker);uimenu('parent',CCC,'label','x','callback',@Marker);
uimenu('parent',CCC,'label','s','callback',@Marker);uimenu('parent',CCC,'label','d','callback',@Marker);
uimenu('parent',CCC,'label','^','callback',@Marker);uimenu('parent',CCC,'label','>','callback',@Marker);
uimenu('parent',CCC,'label','<','callback',@Marker);uimenu('parent',CCC,'label','p','callback',@Marker);
uimenu('parent',CCC,'label','h','callback',@Marker);CCCC=uimenu('parent',CM,'label','MarkerSize');
uimenu('parent',CCCC,'label','2','callback',@MarkerSize);uimenu('parent',CCCC,'label','4','callback',@MarkerSize);
uimenu('parent',CCCC,'label','6','callback',@MarkerSize);uimenu('parent',CCCC,'label','8','callback',@MarkerSize);
uimenu('parent',CCCC,'label','10','callback',@MarkerSize);uimenu('parent',CCCC,'label','12','callback',@MarkerSize);
uimenu('parent',CCCC,'label','14','callback',@MarkerSize);uimenu('parent',CCCC,'label','16','callback',@MarkerSize);
uimenu('parent',CCCC,'label','18','callback',@MarkerSize);uimenu('parent',CCCC,'label','20','callback',@MarkerSize);
CCCCC=uimenu('parent',CM,'label','Linewidth');uimenu('parent',CCCCC,'label','0.5','callback',@Linewidth);
uimenu('parent',CCCCC,'label','1','callback',@Linewidth);uimenu('parent',CCCCC,'label','1.5','callback',@Linewidth);
uimenu('parent',CCCCC,'label','2','callback',@Linewidth);uimenu('parent',CCCCC,'label','2.5','callback',@Linewidth);
uimenu('parent',CCCCC,'label','3','callback',@Linewidth);uimenu('parent',CCCCC,'label','3.5','callback',@Linewidth);
uimenu('parent',CCCCC,'label','4','callback',@Linewidth);
% uimenu('parent',CM,'label','Save','callback',@Save);
% uimenu('parent',CM,'label','New Figure','callback',@NewFigure);
% uimenu('parent',CM,'label','Subplot','callback',@Subplot);
%% =================================== Help ===============================
tab9=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="blue"><b>Help</font></html>');
help(tab9)
tab10=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="k"><b>Contact</font></html>');
contact(tab10)
%% ========================= Variables ====================================
Data=0;FF=0;str=0;Input=0;Inputch=0;values=0;DataFilter=0;fss=0;xf=0;Sigma=0;
spikes=0;index=0;timspk=0;Diff1=0;PcaSpik=0;pcafea=0;waveletSpik=0;wavfea=0;InputClust=0;
Labels=0;Raster=0;MeanSpike=0;MeanPhaseSpaces=0;Firing_Rate=0;Time_Firing=0;ISI=0;
ISI_centers=0;Autoc=0;Xbin=0;
%% ================= Setting callbacks ==================================
set(S.load,'callback',{@Load_Callback,S});set(S.text1,'callback',{@Text1_Callback,S});
set(S.radio,'callback',{@Radio_Callback,S});set(S.inp,'callback',{@Inp_Callback,S});
set(S.radio1,'callback',{@Radio1_Callback,S});set(S.input,'callback',{@Input_Callback,S});
set(S.Chi,'Callback',{@CHi_Callback,S});set(S.Chj,'Callback',{@CHj_Callback,S});

set(S.notch,'callback',{@Notch_Callback,S});set(S.Fnotch,'callback',{@FNotch_Callback,S});
set(S.design,'callback',{@Design_Callback,S});set(S.response,'callback',{@Response_Callback,S});
set(S.fs,'callback',{@Fs_Callback,S});set(S.order,'callback',{@Order_Callback,S});
set(S.fl,'callback',{@Fl_Callback,S});set(S.fh,'callback',{@Fh_Callback,S});
set(S.rp,'callback',{@Rp_Callback,S});set(S.rs,'callback',{@Rs_Callback,S});
set(S.window,'callback',{@Window_Callback,S});set(S.checkFil,'callback',{@CheckFil_Callback,S});
set(S.display,'callback',{@Display_Callback,S});set(S.time,'callback',{@Time_Callback,S});
set(S.time1,'callback',{@Time1_Callback,S});set(S.time2,'callback',{@Time2_Callback,S});
set(S.saveresult,'callback',{@Saveresult_Callback,S});

set(S.inputs,'SelectionChangeFcn',{@Inputs_Callback,S});set(S.detec,'SelectionChangeFcn',{@Detec_Callback,S})
set(S.thresh,'SelectionChangeFcn',{@Thresh_Callback,S});set(S.thrmi,'Callback',{@Thrmi_Callback,S});
set(S.thrmineg,'Callback',{@Thrmineg_Callback,S});set(S.thrma,'Callback',{@Thrma_Callback,S});
set(S.pre,'Callback',{@Pre_Callback,S});set(S.pos,'Callback',{@Pos_Callback,S});
set(S.pren,'Callback',{@Pren_Callback,S});set(S.posn,'Callback',{@Posn_Callback,S});
set(S.alig,'Callback',{@Alig_Callback,S});set(S.Exec,'Callback',{@EXec_Callback,S});
set(S.time3,'Callback',{@Time3_Callback,S});set(S.time4,'Callback',{@Time4_Callback,S});
set(S.time5,'Callback',{@Time5_Callback,S});set(S.time6,'Callback',{@Time6_Callback,S});
set(S.waw,'Callback',{@Waw_Callback,S});set(S.slid1,'Callback',{@Slid1_Callback,S});
set(S.slid2,'Callback',{@Slid2_Callback,S});set(S.dspikeven,'Callback',{@Dspikeven_Callback,S});
set(S.dphaspace,'Callback',{@Dphaspace_Callback,S});set(S.sevent,'Callback',{@Sevent_Callback,S});
set(S.sspike,'Callback',{@Sspike_Callback,S});set(S.sphase,'Callback',{@Sphase_Callback,S});

set(S.Tikpca,'Callback',{@TIkpca_Callback,S});set(S.Feat1,'Callback',{@FEat1_Callback,S});
set(S.Feat2,'Callback',{@FEat2_Callback,S});set(S.Feat3,'Callback',{@FEat3_Callback,S});
set(S.dispca,'Callback',{@Dispca_Callback,S});set(S.Tikwavelet,'Callback',{@TIkwavelet_Callback,S});
set(S.wave,'Callback',{@Wave_Callback,S});set(S.leve,'Callback',{@Leve_Callback,S});
set(S.Feat31,'Callback',{@FEat31_Callback,S});set(S.Feat32,'Callback',{@FEat32_Callback,S});
set(S.Feat33,'Callback',{@FEat33_Callback,S});set(S.diswave,'Callback',{@Diswave_Callback,S});
set(S.Plot,'SelectionChangeFcn',{@PLot_Callback,S});set(S.spca,'Callback',{@Spca_Callback,S});
set(S.swavelet,'Callback',{@Swavelet_Callback,S});

set(S.inpclust,'Callback',{@Inpclust_Callback,S});set(S.plotc,'Callback',{@Plotc_Callback,S});
set(S.center,'SelectionChangeFcn',{@Center_Callback,S});set(S.cursor,'Callback',{@Cursor_Callback,S});
set(S.clus,'Callback',{@Clus_Callback,S});set(S.numcl,'Callback',{@Numcl_Callback,S});
set(S.plotR,'Callback',{@PlotR_Callback,S});set(S.plotSU,'Callback',{@PlotSU_Callback,S});
set(S.plotPhU,'Callback',{@PlotPhU_Callback,S});set(S.sraster,'Callback',{@Sraster_Callback,S});
set(S.sspikeuint,'Callback',{@Sspikeuint_Callback,S});set(S.sphaseuint,'Callback',{@Sphaseuint_Callback,S});
set(S.time7,'Callback',{@Time7_Callback,S});set(S.time8,'Callback',{@Time8_Callback,S});
set(S.Xlim,'Callback',{@XLim_Callback,S});set(S.slid3,'Callback',{@Slid3_Callback,S});
set(S.plotspikesort,'SelectionChangeFcn',{@Plotspikesort_Callback,S});

set(S.binTime,'Callback',{@BinTime_Callback,S});set(S.binFR,'Callback',{@BinFR_Callback,S});
set(S.sfringrate,'Callback',{@Sfringrate_Callback,S});set(S.plotFR,'SelectionChangeFcn',{@PlotFR_Callback,S});
set(S.minInte,'Callback',{@MinInte_Callback,S});set(S.maxnInte,'Callback',{@MaxnInte_Callback,S});
set(S.bin,'Callback',{@Bin_Callback,S});set(S.plotISI,'Callback',{@PlotISI_Callback,S});
set(S.sISI,'Callback',{@SISI_Callback,S});set(S.plotautogram,'Callback',{@Plotautogram_Callback,S});
set(S.sautogram,'Callback',{@Sautogram_Callback,S});
%% ====================================== Step 1 ===============================================
function Load_Callback(~,~,handles);[str,FF,Data,values]=load_data(handles.inp,handles.text1);end %Load
function Radio_Callback(~, ~, ~)
[Inputch,DataFilter,Input,fss,Sigma,xf,index,spikes,timspk,Diff1,PcaSpik,pcafea,waveletSpik,...
wavfea,InputClust,Labels,Raster,MeanSpike,MeanPhaseSpaces,Firing_Rate,Time_Firing,ISI,...
ISI_centers,Autoc,Xbin]=clear_parameters(S);end %clear Parameters
function Inp_Callback(~, ~, handles) %Input
[Inputch,DataFilter]=select_input(Data,str,values,FF,handles.radio,handles.input,handles.inp,handles.radio1);
end
function Input_Callback(~,~,handles) %Channel
Input=select_channels(Inputch,handles.Chi,handles.Chj,handles.input,handles.inp,handles.checkFil);end
%% ====================================== Step 2 ===============================================
function Design_Callback(~, ~, handles)
[DataFilter,fss,Sigma]=data_filtered(Input,handles.fs,handles.fl,handles.fh,handles.rp,...
handles.rs,handles.order,handles.design,handles.response,handles.window,handles.checkFil,...
handles.Fnotch,handles.notch,handles.display,handles.tabel,handles.time1,handles.time2,...
handles.time,S);
end
function Display_Callback(~, ~, handles) %PLOT Filter  
plot_filter(Input,DataFilter,fss,handles.design,handles.display,handles.input,handles.time,...
handles.time1,handles.time2,S.ax(1),S.ax(2),CM,cm)  
end
%% ====================================== Step 3 ===============================================
function Inputs_Callback(~, ~, handles)
[xf, Sigma]=input_spike(Data,DataFilter,handles.inputs,handles.thrmi,handles.thrma,...
handles.thrmineg,handles.time3,handles.time4,handles.time5,handles.time6,S);    
end
function Thresh_Callback(~, ~, handles) % Threshold 
[index,spikes,timspk]=threshold(xf,fss,Sigma,handles.detec,handles.thresh,handles.thrmi,...
handles.thrmineg,handles.thrma,handles.pre,handles.pos,handles.pren,handles.posn,...
handles.alig,handles.Exec,handles.time3,handles.time4,handles.time5,handles.time6,...
handles.waw,handles.slid1,handles.slid2,S.tabe2,S.ax(3),S.ax(4),S.ax(5),CM,cm,S);    
end 
function Dspikeven_Callback(~, ~,handles);plot_spike_event(spikes,fss,handles.dspikeven,S.ax(6),cm);end % Plot Spike Events 
function Dphaspace_Callback(~, ~,handles);Diff1=plot_phase_spaces(spikes,handles.dphaspace,S.ax(7),cm);end % Plot Phase Spaces
%% ======================================= Step 4 ==============================================
function TIkpca_Callback(~, ~, handles) %PCA
PcaSpik = pca_feature(spikes,handles.Tikpca,handles.dispca,handles.diswave);end
function Dispca_Callback(~, ~, handles) %PCA
pcafea = plot_pca(spikes,PcaSpik,handles.Feat1,handles.Feat2,handles.Feat3,handles.dispca,...
handles.diswave,S.ax(8),S.ax(9),S.ax(10),S.ax(11),cm,S);end
function TIkwavelet_Callback(~, ~, handles) %Wavelet 
waveletSpik = wavelet_feature(spikes,handles.Tikwavelet,handles.wave,handles.leve,...
handles.dispca,handles.diswave);end
function Diswave_Callback(~, ~, handles) %Wavelet
wavfea = plot_wavelet(spikes, waveletSpik,handles.Feat31,handles.Feat32,handles.Feat33,...
handles.dispca,handles.diswave,S.ax(8),S.ax(9),S.ax(10),S.ax(11),cm,S);end
%% ======================================= Step 5 ==============================================
function Inpclust_Callback(~, ~, handles) % Cluster 
InputClust = input_cluster(pcafea,wavfea,handles.plotc,handles.inpclust,handles.cursor,...
handles.numcl,S.ax(12),cm,S);
end
function Clus_Callback(~, ~, handles) 
Labels = clustering(InputClust,handles.clus,handles.numcl,handles.inpclust,S.ax(13),S,cm);
end
function PlotR_Callback(~, ~, handles) 
Raster = plot_raster(xf,index,Labels,fss,handles.plotR,handles.time4,S.ax(14),cm);    
end
function PlotSU_Callback(~, ~, handles) 
MeanSpike = plot_cluster_spike_events(spikes,Labels,fss,handles.plotSU,S.ax(15),cm);    
end
function PlotPhU_Callback(~, ~, handles) 
MeanPhaseSpaces = plot_cluster_phasespaces(spikes,Labels,handles.plotPhU,S.ax(16),cm);    
end
function Plotspikesort_Callback(~, ~, handles) 
plot_spikesorting(xf,spikes,timspk,Labels,index,fss,handles.time7,handles.time8,...
handles.Xlim,handles.slid3,handles.tabe3,S.ax(17),S.ax(18),cm,S);    
end
%% ======================================== Step 6 =============================================
function BinFR_Callback(~, ~, handles) %Firing rate
[Firing_Rate,Time_Firing] = firing_rate(xf,fss,index,Labels,handles.binTime,handles.binFR,S);
end
function PlotFR_Callback(~, ~, handles)
plot_firing_rate(Firing_Rate,Time_Firing,handles.binTime,handles.binFR,S.ax(19),S.ax(20),cm,S);
end
function MaxnInte_Callback(~, ~, handles) %ISI
[ISI,ISI_centers,Autoc,Xbin]=isi(index,Labels,fss,handles.binTime,handles.plotISI,...
handles.plotautogram,handles.maxnInte,handles.minInte,handles.bin);
end
function PlotISI_Callback(~, ~, handles)
plot_isi(ISI,ISI_centers,handles.plotISI,handles.bin,S.ax(21),S.ax(22),cm)
end
function Plotautogram_Callback(~, ~, handles) %Autocorrelogram
plot_autogram(Autoc,Xbin,handles.plotautogram,handles.maxnInte,handles.minInte,...
handles.bin,S.ax(23),S.ax(24),cm);end
%% ======================================= Figure ============================================== 
function NewFigure(~,~,~) %NewFigure
ax=gca;fig_new=figure('unit','norm','pos',[0.1 0.45 0.8 0.35]);
axes_new=copyobj(ax,fig_new);set(axes_new,'unit','norm','outerposition',[.03 .03 .95 .95])
if ~isempty(ax.Legend);til=legend(ax.Legend.String);if ~isempty(ax.Legend.Title.String)
title(til,ax.Legend.Title.String);end;end
end
function Subplot(~,~,~);ax=gca;fig_new1=figure(2);copyobj(ax,fig_new1);% Subplot
% if ~isempty(ax.Legend);til=legend(ax.Legend.String);
% if ~isempty(ax.Legend.Title.String);title(til,ax.Legend.Title.String);end;end;
end 
%% ===================================== Save Figure ===========================================
function Save(~,~,~)
ax=gca;h=get(ax,'position');%axes1=axes1.Parent;
fig_new=figure('unit','norm','pos',h,'Visible','off');
axes_new=copyobj(ax,fig_new);set(axes_new,'unit','norm','outerposition',[.03 .03 .95 .95])
if ~isempty(ax.Legend);til=legend(ax.Legend.String);
if ~isempty(ax.Legend.Title.String);title(til,ax.Legend.Title.String);end;end
fn=uiputfile({'*.jpg';'*.png';'*.fig'});
if fn~=0;saveas(axes_new,fn);msgbox('Operation Completed');end;close(fig_new)
end
%% ======================================= Save Data ===========================================
function Saveresult_Callback(~,~,handles)
if get(handles.saveresult,'value')==1; set(handles.saveresult,'value',0);    
if DataFilter==0;msgbox('Please select Parameters in Block Filtering','','warn');return;end
Output=DataFilter;
elseif get(handles.sevent,'value')==1; set(handles.sevent,'value',0);
if index==0; msgbox('Please select Parameters in Block Spike Detection','','warn');return;end
Output=index';
elseif get(handles.sspike,'value')==1; set(handles.sspike,'value',0);
if spikes==0;msgbox('Please select Parameters in Block Spike Detection','','warn');return;end
Output=spikes;
elseif get(handles.sphase,'value')==1;set(handles.sphase,'value',0)
if Diff1==0;msgbox('Please select Parameters in Block Spike Detection','','warn');return;end
Output=Diff1;
elseif get(handles.spca,'value')==1;set(handles.spca,'value',0);
if pcafea==0;msgbox('Please select PCA Analysis','','warn');return;end;Output=pcafea;    
elseif get(handles.swavelet,'value')==1;set(handles.swavelet,'value',0);
if wavfea==0;msgbox('Please select Wavelet Analysis','','warn');return;end;Output=wavfea;  
elseif get(handles.sraster,'value')==1;set(handles.sraster,'value',0);
if Raster==0;msgbox('Please select Save Raster','','warn');return;end;Output=Raster;  
elseif get(handles.sspikeuint,'value')==1;set(handles.sspikeuint,'value',0);
if MeanSpike==0;msgbox('Please select Save Clustered Spike Events','','warn');return;end;Output=MeanSpike';
elseif get(handles.sphaseuint,'value')==1;set(handles.sphaseuint,'value',0);
if MeanPhaseSpaces==0;msgbox('Please select Save Clustered Phase Spaces','','warn');return;end;Output=MeanPhaseSpaces'; 
elseif get(handles.sfringrate,'value')==1;set(handles.sfringrate,'value',0);
if Firing_Rate==0;msgbox('Please Enter Parameters ISI & Autocorrelogram','','warn');return;end;Output=[Time_Firing',Firing_Rate'];  
elseif get(handles.sISI,'value')==1;set(handles.sISI,'value',0);
if ISI==0;msgbox('Please Enter Parameters ISI & Autocorrelogram','','warn');return;end;Output=[ISI_centers',ISI'];  
elseif get(handles.sautogram,'value')==1;set(handles.sautogram,'value',0);
if Autoc==0;msgbox('Please Enter Parameters ISI & Autocorrelogram','','warn');return;end;Output=[Xbin',Autoc'];  
end
[fn,~,ind]=uiputfile({'*.mat';'*.txt'});
if fn~=0;if ind==1;save(fn,'Output');elseif ind==2;save(fn,'Output','-ascii');end
msgbox('Operation Completed');
end
end
%% ====================================== Callback =============================================
function Color(~,~,~)
    a=get(gcbo,'label');
    set(gco,'Color',get(gcbo,'label'));end 
function Linestyle(~,~,~);set(gco,'Linestyle',get(gcbo,'label'));end
function Marker(~,~,~);set(gco,'Marker',get(gcbo,'label'));end
function MarkerSize(~,~,~);set(gco,'MarkerSize',str2double(get(gcbo,'label')));end
function Linewidth(~,~,~);set(gco,'Linewidth',str2double(get(gcbo,'label')));end 

function Radio1_Callback(~,~,handles);Inp_Callback(handles.inp,nan,handles);end 
function FNotch_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Notch_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Fs_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Fl_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Fh_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Order_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Rp_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Rs_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Response_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
function Window_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end
function CheckFil_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end
function CHi_Callback(~, ~, handles);Input_Callback(handles.input,nan,handles);end 
function CHj_Callback(~, ~, handles);Input_Callback(handles.input,nan,handles);end 
function Time_Callback(~, ~, handles);Display_Callback(handles.display,nan,handles);end 
function Time1_Callback(~, ~, handles);Display_Callback(handles.display,nan,handles);end 
function Time2_Callback(~, ~, handles);Display_Callback(handles.display,nan,handles);end 
    
function Detec_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Thrmi_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Thrma_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Thrmineg_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Pre_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Pos_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Pren_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Posn_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Alig_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function EXec_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end 
function Time3_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end
function Time4_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end
function Time5_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end
function Time6_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end
function Waw_Callback(~, ~, handles);Thresh_Callback(handles.thresh,nan,handles);end
function Sevent_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
function Sspike_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
function Sphase_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end

function FEat1_Callback(~, ~, handles);Dispca_Callback(handles.dispca,nan,handles);end
function FEat2_Callback(~, ~, handles);Dispca_Callback(handles.dispca,nan,handles);end
function FEat3_Callback(~, ~, handles);Dispca_Callback(handles.dispca,nan,handles);end
function FEat31_Callback(~, ~, handles);Diswave_Callback(handles.diswave,nan,handles);end
function FEat32_Callback(~, ~, handles);Diswave_Callback(handles.diswave,nan,handles);end
function FEat33_Callback(~, ~, handles);Diswave_Callback(handles.diswave,nan,handles);end
function Leve_Callback(~, ~, handles);TIkwavelet_Callback(handles.Tikwavelet,nan,handles);end
function Wave_Callback(~, ~, handles);TIkwavelet_Callback(handles.Tikwavelet,nan,handles);end
function PLot_Callback(~, ~, handles)
if get(handles.dispca,'value')==1;Dispca_Callback(handles.dispca,nan,handles);
elseif get(handles.diswave,'value')==1;Diswave_Callback(handles.diswave,nan,handles);end
end
function Spca_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
function Swavelet_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end

function Plotc_Callback(~, ~, handles);Inpclust_Callback(handles.inpclust,nan,handles);end
function Cursor_Callback(~, ~, handles);Inpclust_Callback(handles.inpclust,nan,handles);end
function Numcl_Callback(~, ~, handles);Clus_Callback(handles.clus,nan,handles);end
function Center_Callback(~, ~, handles);Clus_Callback(handles.clus,nan,handles);end
function Time7_Callback(~, ~, handles);Plotspikesort_Callback(handles.plotspikesort,nan,handles);end
function Time8_Callback(~, ~, handles);Plotspikesort_Callback(handles.plotspikesort,nan,handles);end
function XLim_Callback(~, ~, handles);Plotspikesort_Callback(handles.plotspikesort,nan,handles);end
function Sraster_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
function Sspikeuint_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
function Sphaseuint_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
    
function BinTime_Callback(~, ~, handles);BinFR_Callback(handles.binFR,nan,handles);end
function Sfringrate_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
function MinInte_Callback(~, ~, handles);MaxnInte_Callback(handles.maxnInte,nan,handles);end
function Bin_Callback(~, ~, handles);MaxnInte_Callback(handles.maxnInte,nan,handles);end
function SISI_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
function Sautogram_Callback(~, ~, handles);Saveresult_Callback(handles.saveresult,nan,handles);end
end